### ISSUE TITLE
Indexing and query worflow for ACCESS-OM non-CMIP data (cj50)

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ACCESS-MED#63]
OK I know the data in `cj50` are far from organised and there is quite a range of cases to cover...

What we want to have:

Indexing of experiments so we can query for:

- experiment name
- variable
- start-time
- end-time
- frequency

Tasks (Feel free to edit):

- [x] COSIMA parser
- [x] Indexing of COSIMA collection (cj50) (legacy-support control data only, see https://forum.access-hive.org.au/t/access-om2-control-runs/258)
- [x] Simple example in the form of a Jupyter notebook where people can load data from COSIMA
- [x] Simple example on how to compare COSIMA outputs with CMIP data using the NCI Intake Catalog

**Comment by dougiesquire** [comment]
See https://github.com/ACCESS-NRI/nri_intake_catalog/tree/main/notebooks for some example Jupyter notebooks
