### ISSUE TITLE
Indexing and query worflow for ACCESS-ESM non-CMIP data

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ACCESS-MED#64]
Indexing of experiments so we can query for:

- experiment name
- variable
- start-time
- end-time
- frequency

Tasks (Feel free to edit):

- [x] ACCESS-ESM Native format parser
- [x] Indexing of ACCESS-ESM non-CMIP collection (p73, others?)
- [x] Simple example in the form of a Jupyter notebook where people can load data .
- [x] Simple example on how to compare ACCESS-ESM outputs with CMIP data using the NCI Intake Catalog

**Comment by dougiesquire** [comment]
@MartinDix what are some example experiments we might like to include?

**Comment by rbeucher** [comment]
Do we need multiple examples?

- historical
- pre-industrial etc.

**Comment by rbeucher** [comment]
Arnold has some simple examples he used for the ACCESS Workshop at AMOS: https://github.com/ars599/ACCESS-AMOS22

**Comment by dougiesquire** [comment]
I'd like some "real" model experiments (i.e. lots of data). Maybe I'll start with what's in `/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5`?

**Comment by rbeucher** [comment]
That's the one I was looking at

**Comment by dougiesquire** [comment]
See https://github.com/ACCESS-NRI/intake_catalog/issues/5

**Comment by dougiesquire** [comment]
See https://github.com/ACCESS-NRI/nri_intake_catalog/tree/main/notebooks for some example Jupyter notebooks
