### ISSUE TITLE
Indexing and query worflow for ACCESS-CM non-CMIP data

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ACCESS-MED#65]
Indexing of experiments so we can query for:

- experiment name
- variable
- start-time
- end-time
- frequency

Tasks (Feel free to edit):

- [x] ACCESS-CM Native format parser
- [x] Indexing of ACCESS-CM non-CMIP collection
- [x] Simple example in the form of a Jupyter notebook where people can load data .
- [x] Simple example on how to compare ACCESS-CM outputs with CMIP data using the NCI Intake Catalog

**Comment by dougiesquire** [comment]
@MartinDix what are some example experiments we might like to include?

**Comment by dougiesquire** [comment]
Maybe start with what's in `/g/data/p73/archive/non-CMIP/ACCESS-CM2`?

**Comment by dougiesquire** [comment]
See https://github.com/ACCESS-NRI/intake_catalog/issues/5

**Comment by dougiesquire** [comment]
See https://github.com/ACCESS-NRI/nri_intake_catalog/tree/main/notebooks for some example Jupyter notebooks
